### ISSUE TITLE
Improve status command output

### ISSUE THREAD

**Issue by andriygm** [A2-ai/devious#11]
```[tasklist]
### Tasks
- [x] Show file size
- [ ] Show total storage of tracked files both locally and in storage
- [ ] Show if file is up to date
```

Creator might not be necessary since you can just look at the git commit
