### ISSUE TITLE
Create test cases

### ISSUE THREAD

**Issue by andriygm** [A2-ai/devious#4]
```[tasklist]
### Tasks
- [x] Duplicate gitignore entries
- [x] Getting a file that no longer exists in storage
- [ ] Dir to drop metadata file is not writeable
- [x] Storage dir is not writable
- [x] Parent of desired storage dir doesn't exist
- [x] Config already exists
- [ ] Parent of storage dir is not writable
```
